name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rollback on failure
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' << 'EOF'
            set -e

            cd ~/tg2kindle

            echo "[1] Saving current commit..."
            CURRENT_COMMIT=$(git rev-parse HEAD)
            echo $CURRENT_COMMIT > .last_commit

            echo "[2] Pulling latest changes..."
            if ! git pull; then
              echo "[ERR] Git pull failed. Aborting."
              exit 1
            fi

            echo "[3] Restarting bot..."
            if ! sudo systemctl restart telegram-bot; then
              echo "[ERR] Restart failed. Rolling back..."
              git reset --hard $(cat .last_commit)
              sudo systemctl restart telegram-bot
              echo "[OK] Rolled back and restarted previous version."
              exit 1
            fi

            echo "[OK] Deployment successful."
          EOF
