name: Deploy with rollback + Telegram alerts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rollback + Telegram alerts
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' << 'EOF'
            set -e
            cd ~/tg2kindle

            echo "[1] Saving current commit..."
            CURRENT_COMMIT=$(git rev-parse HEAD)
            echo $CURRENT_COMMIT > .last_commit

            echo "[2] Pulling latest changes..."
            if ! git pull; then
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TG_CHAT_ID }} \
                -d text="🚨 *Deploy failed during git pull* on *tg2kindle*."
              exit 1
            fi

            echo "[3] Restarting bot..."
            if ! sudo systemctl restart telegram-bot; then
              echo "[ERR] Restart failed. Rolling back..."
              git reset --hard $(cat .last_commit)
              sudo systemctl restart telegram-bot
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TG_CHAT_ID }} \
                -d text="⚠️ *Rollback triggered on tg2kindle*. Previous version restored."
              exit 1
            fi

            curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TG_CHAT_ID }} \
              -d text="✅ *tg2kindle deployed successfully* and bot restarted."

            echo "[OK] Deployment successful."
          EOF
